var talents = [
    { 
      id: "bloodthirst",
      name: "Bloodthirst",
      icon: "abilityIconString(Hero.JUNKER_QUEEN, Button.ABILITY_1)",
      keybind: '"[Passive]"',
      description: "Heal yourself based on how much damage you dealt during berserker. Health can be overhealed. Overhealed health slowly decay.",
      comment: "The healing amount will scale with the duration of berserker. Cancel Berserker early to receive more healing.",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Healing]",
      cd_reduction_per_rank: 0,
      requires_any_of: ["berserker"],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "purity_field",
      name: "Purity Field",
      icon: "abilityIconString(Hero.BAPTISTE, Button.ABILITY_2)",
      keybind: '"[Double Tap: [CTRL]]"',
      description: "Activate to exit combat, become immune and increase your healing received. Can not use damage abilities while immune.",
      comment: "Can be used to be able to escape with Hearthstone, enter Stealth or heal yourself with bandage without getting interrupted.",
      cooldown: 45,
      upgrade_information: "[Upgrade: +Duration, +Healing Received]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "cybernetics",
      name: "Cybernetics",
      icon: "abilityIconString(Hero.SOMBRA, Button.SECONDARY_FIRE)",
      keybind: '"[Passive]"',
      description: "Add permanent shields to your health. Shields regenerate automatically and can't be healed with healing abilities.",
      comment: "Shields start regenerating when you exit combat.",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Shields]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "soul_harvest",
      name: "Soul Harvest",
      icon: "abilityIconString(Hero.MOIRA, Button.SECONDARY_FIRE)",
      keybind: '"[Passive]"',
      description: "Picking up XP orbs will heal you.",
      comment: "Combine with a talent that increase your mobility to reach orbs faster than others!",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Healing]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "poisonous_dagger",
      name: "Poisonous Dagger",
      icon: "abilityIconString(Hero.JUNKER_QUEEN, Button.SECONDARY_FIRE)",
      keybind: '"[[MELEE] (In Stealth)]"',
      description: "Your melee in stealth will debuff your target with a poison that deal damage after 5s.",
      comment: "",
      cooldown: 20,
      upgrade_information: "[Upgrade: +Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: ["stealth"],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
  
    },
    { 
      id: "stealth",
      name: "Stealth",
      icon: "abilityIconString(Hero.REAPER, Button.ABILITY_1)",
      keybind: '"[Hold: [CTRL]]"',
      description: "Enter stealth when crouching out of combat. Melee from stealth will stun the target.",
      comment: "Taking damage or using damage dealing abilities will break stealth.",
      cooldown: 10,
      upgrade_information: "[Upgrade: +Stealth Duration, +Stun Duration]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: "poisonous_dagger",
    },
    { 
      id: "juggernaut",
      name: "Juggernaut",
      icon: "abilityIconString(Hero.DOOMFIST, Button.SECONDARY_FIRE)",
      keybind: '"[[F]]"',
      description: "Activate to start sprinting. Hitting a player will stun them and pick them up. Hitting a wall will damage players around you.",
      comment: "When using the ability: Immune to knockback and slows.",
      cooldown: 20,
      upgrade_information: "[Upgrade: +Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: true,
      conflicts_with: ["fireball"],
      expand_mind: null,
    },
    { 
      id: "dive_bomb",
      name: "Dive Bomb",
      icon: "abilityIconString(Hero.HAMMOND, Button.CROUCH)",
      keybind: '"[[CTRL] (In Air)]"',
      description: "Gain the ability to dive down on players from the air. Targets hit will be knocked away and take damage.",
      comment: "Must be activated at least 3.5m above the ground. Damage is increased the longer you stay in air (up to 1s).",
      cooldown: 20,
      upgrade_information: "[Upgrade: +Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "cryogenics",
      name: "Cryogenics",
      icon: "abilityIconString(Hero.MEI, Button.ULTIMATE)",
      keybind: '"[[RIGHTCLICK]]"',
      description: "Your secondary fire will slow enemies. Affected targets can't use sprint.",
      comment: "",
      cooldown: 6,
      upgrade_information: "[Upgrade: +Slow Amount, +Slow Duration]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "railgun",
      name: "Railgun",
      icon: "abilityIconString(Hero.SOJOURN, Button.SECONDARY_FIRE)",
      keybind: '"[[RIGHTCLICK] + [LEFTCLICK]]"',
      description: "Replace your secondary fire with a railgun attachment. Railgun will count as your secondary fire.",
      comment: "Hitscan ability. Headshots will deal double damage.",
      cooldown: 6,
      upgrade_information: "[Upgrade: +Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [/*"bombardment"*/],
      expand_mind: "overclock",
    },
    { 
      id: "grim_reaper",
      name: "Grim Reaper",
      icon: "('<tx0C0000000004F741>')",
      keybind: '"[[F]]"',
      description: "See low-health players. Cast to project yourself to your target.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Cast Speed, +Flight Speed]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: true,
      conflicts_with: ["fireball"],
      expand_mind: null,
    },
    { 
      id: "jetpack",
      name: "Jetpack",
      icon: "('<tx0C000000000721CB>')",
      keybind: '"[Hold: [SPACEBAR]]"',
      description: "Equip a Jetpack that will let you fly.",
      comment: "Combine with Dive Bomb to more easily do heavy damage. Flying in stealth makes no sound.",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Fuel Efficiency]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "lifesteal_ammo",
      name: "Lifesteal Ammo",
      icon: "abilityIconString(Hero.BAPTISTE, Button.SECONDARY_FIRE)",
      keybind: '"[[LEFTCLICK] or [RIGHTCLICK]]"',
      description: "A percentage of the damage you deal with primary fire or secondary fire will heal you.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Healing]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "health_regen",
      name: "Health Regen",
      icon: "abilityIconString(Hero.BAPTISTE, Button.ABILITY_1)",
      keybind: '"[Passive]"',
      description: "Passively regenerate health over time.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Healing]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "health_potions",
      name: "Health Potions",
      icon: "abilityIconString(Hero.ROADHOG, Button.ABILITY_2)",
      keybind: '"[[E]]"',
      description: "Buy 3 Health Potions. Each potion vial refills one at a time each 15s.",
      comment: "Each potion applies its healing over 2 seconds.",
      cooldown: 15,
      upgrade_information: "[Upgrade: +Healing]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: "alchemist",
    },
    { 
      id: "ignite",
      name: "Ignite",
      icon: "iconString(Icon.FIRE)",
      keybind: '"[[RIGHTCLICK]]"',
      description: "A percentage of the damage you deal with secondary fire also deals fire damage over time.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "overclock",
      name: "Overclock",
      icon: "abilityIconString(Hero.TORBJORN, Button.ABILITY_2)",
      keybind: '"[Passive]"',
      description: "Reduces the cooldown of Railgun.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: -Cooldown]",
      cd_reduction_per_rank: 0,
      requires_any_of: ["railgun"],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "shadowstep",
      name: "Shadowstep",
      icon: "abilityIconString(Hero.MOIRA, Button.ABILITY_1)",
      keybind: '"[Double Tap: [SPACEBAR]]"',
      description: "Leap in any direction, become invisible and invulnerable for 0.5s. XP Orbs will reset the cooldown.",
      comment: "",
      cooldown: 22.5,
      upgrade_information: "[Upgrade: -Cooldown]",
      cd_reduction_per_rank: 2.5,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "burning_soul",
      name: "Burning Soul",
      icon: "abilityIconString(Hero.REAPER, Button.ULTIMATE)",
      keybind: '"[Passive]"',
      description: "Deal damage to nearby, visible players when not sprinting. Enemies take damage from your XP orb if picked up before 4s",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "berserker",
      name: "Berserker",
      icon: "iconString(Icon.SKULL)",
      keybind: '"[[Q]]"',
      description: "Activate to Deal 25% more damage and receive 10% more damage temporarily.",
      comment: "",
      cooldown: 45,
      upgrade_information: "[Upgrade: +Duration]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: "bloodthirst",
    },
    { 
      id: "fireball",
      name: "Fireball",
      icon: "abilityIconString(Hero.PHARAH, Button.ABILITY_1)",
      keybind: '"[[F]]"',
      description: "Install a weapon attachment that will let you launch fireballs.",
      comment: "",
      cooldown: 20,
      upgrade_information: "[Upgrade: +Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: true,
      conflicts_with: ["grim_reaper"],
      expand_mind: "pyromaniac",
    },
    { 
      id: "ignore_pain",
      name: "Ignore Pain",
      icon: "abilityIconString(Hero.ZARYA, Button.ABILITY_1)",
      keybind: '"[Passive]"',
      description: "Resist a lot of damage while you are casting, reloading, sprinting or stunned.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Damage Resistance]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: true,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "javelin",
      name: "Javelin",
      icon: "abilityIconString(Hero.ORISA, Button.SECONDARY_FIRE)",
      keybind: '"[Passive]"',
      description: "Gain the ability to throw a javelin that deals damage, stuns and knocks back the player hit.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "bandage",
      name: "Bandage",
      icon: "abilityIconString(Hero.KIRIKO, Button.PRIMARY_FIRE)",
      keybind: '"[Double Tap: [MELEE]]"',
      description: "Instantly clear all your debuffs and heal yourself up over 10s. Reduces movement speed. Interrupted if taking damage.",
      comment: "Can not remove stuns.",
      cooldown: 30,
      upgrade_information: "[Upgrade: +Healing]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "pyromaniac",
      name: "Pyromaniac",
      icon: "('<tx0C000000000144A8>')",
      keybind: '"[Passive]"',
      description: "Your Fireball will heal you if you stand near the explosion radius.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Healing]",
      cd_reduction_per_rank: 0,
      requires_any_of: ["fireball"],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    { 
      id: "poison_vials",
      name: "Poison Vials",
      icon: "iconString(Icon.POISON_2)",
      keybind: '"[[E]]"',
      description: "Targets hit will take damage over time.",
      comment: "The damage of the poison vials stack.",
      cooldown: 15,
      upgrade_information: "[Upgrade: +Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: true,
      conflicts_with: ["health_potions"],
      expand_mind: "alchemist",
    },
    { 
      id: "alchemist",
      name: "Alchemist",
      icon: "iconString(Icon.RADIOACTIVE)",
      keybind: '"[Passive]"',
      description: "Reduces the cooldown of your Health Potions and gives you a chance to pick up another when picking up XP Orbs.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: -Cooldown, +Chance]",
      cd_reduction_per_rank: 1,
      requires_any_of: ["health_potions", "poison_vials"],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    /*
    { 
      id: "bombardment",
      name: "Bombardment",
      icon: "abilityIconString(Hero.PHARAH, Button.ULTIMATE)",
      keybind: '"[[LEFTCLICK] or [RIGHTCLICK]]"',
      description: "Disable your primary fire and reduce the cooldown of your Helix Rockets from 6s down to 1s.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Helix Rocket Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: true,
      conflicts_with: ["gunslinger", "railgun"],
      expand_mind: null,
    },
    */
    { 
      id: "gigachad",
      name: "Gigachad",
      icon: "abilityIconString(Hero.RAMATTRA, Button.ABILITY_1)",
      keybind: '"[Passive]"',
      description: "Increase your health & headshot resistance, but slightly increase your size.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Health, +Headshot Resist, +Size]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: false,
      conflicts_with: [],
      expand_mind: null,
    },
    /*
    { 
      id: "gunslinger",
      name: "Gunslinger",
      icon: "abilityIconString(Hero.CASSIDY, Button.ULTIMATE)",
      keybind: '"[[LEFTCLICK]]"',
      description: "Reduce your magazine size, your rate of fire and increase damage dealt of primary fire.",
      comment: "",
      cooldown: 0,
      upgrade_information: "[Upgrade: +Primary Fire Damage]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: true,
      conflicts_with: ["bombardment"],
      expand_mind: null,
    },
  
    { 
      id: "adrenaline_rush",
      name: "Adrenaline Rush",
      icon: "abilityIconString(Hero.SOLDIER, Button.ABILITY_1)",
      keybind: '"[[Passive]]"',
      description: "Deal damage to gain Adrenaline. Adrenaline increases your movement speed in stages: 20%, 40%, 60%.",
      comment: "Adrenaline decays over time. Higher ranks require less damage and decay slower.",
      cooldown: 0,
      upgrade_information: "[Upgrade: -Damage Required, +Decay Duration]",
      cd_reduction_per_rank: 0,
      requires_any_of: [],
      is_unique: true,
      conflicts_with: ["ignore_pain"],
      expand_mind: null,
    },
    */
  ]
    
  var result = ""
  result += "globalvar is_talent_unique = ["+talents.map(x => x.is_unique)+"]\n"
  result += "globalvar talent_base_cooldowns = ["+talents.map(x => x.cooldown)+"]\n"
  result += "globalvar talent_cd_reduction_p_rank = ["+talents.map(x => x.cd_reduction_per_rank)+"]\n"
  result += "globalvar talent_names = ["+talents.map(x => `"{} [${x.name}]".format(${x.icon})`)+"]\n"
  result += "globalvar talent_descriptions = ["+talents.map(x => JSON.stringify(x.description))+"]\n"
  result += "globalvar upgrade_information = ["+talents.map(x => JSON.stringify(x.upgrade_information))+"]\n"
  result += "globalvar additional_information = ["+talents.map(x => JSON.stringify(x.comment))+"]\n" 
  result += "globalvar talent_information_unique = ["+talents.map(x => "["+x.conflicts_with.map(x => "Talent."+x.toUpperCase())+"]")+"]\n"
  result += "globalvar talent_information_expand_mind = ["+talents.map(x => x.expand_mind ? "Talent."+x.expand_mind.toUpperCase() : "null")+"]\n" 
  result += "globalvar talent_requirements = ["+talents.map(x => "["+x.requires_any_of.map(x => "Talent."+x.toUpperCase())+"]")+"]\n"
  result += "globalvar talent_keybinds = ["+talents.map(x => x.keybind)+"]\n"

  
  result